# Generated by Django 5.0.7 on 2024-07-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_add_model',
            name='doctor_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
