# Generated by Django 5.0.7 on 2024-08-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Control', '0002_doctor_add_model_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_add_model',
            name='about_me',
            field=models.TextField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='doctor_add_model',
            name='education',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor_add_model',
            name='education_grad_years',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctor_add_model',
            name='education_start_years',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctor_add_model',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='doctor_add_model',
            name='experiance_finish_years',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctor_add_model',
            name='experiance_start_years',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctor_add_model',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor_add_model',
            name='my_skills',
            field=models.TextField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='doctor_add_model',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor_add_model',
            name='speciality',
            field=models.CharField(max_length=100),
        ),
    ]
