# Generated by Django 5.0.7 on 2024-08-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Control', '0004_appointment_model_alter_doctor_add_model_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_model',
            name='email',
            field=models.EmailField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
