# Generated by Django 5.0.7 on 2024-08-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Control', '0005_appointment_model_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment_model',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appointment_model',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='appointment_model',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday')], max_length=3),
        ),
    ]
