# Generated by Django 5.0.7 on 2024-08-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Randevu', '0002_weekly_randevu_model_delete_monday_randevu_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly_randevu_model',
            name='message',
            field=models.CharField(blank=True, default='Control', max_length=250),
        ),
    ]
