# Generated by Django 5.1.1 on 2024-09-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.CharField(max_length=100)),
                ('blog_content', models.CharField(max_length=1500)),
                ('blog_image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
